### PR TITLE
Record drawn items

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes

### What is the current behavior?
Drawing of complex (diagrams) is relatively slow, especially on platforms like macOS.
Although the GtkView already uses a back-buffer, it still needs to `draw()` all elements when the widget is repainted. Worst case it needs to redraw it multiple times: once for bounding box calculation and any number of times to refresh the back buffer.

Issue Number: N/A

### What is the new behavior?

This PR contains a couple of improvements:

* When items are painted for bounding box calculation, the resulting drawing (a cairo surface) is cached, so subsequent drawing operations can reuse this effort.
* A special painter, `RenderedItemPainter`, can be used to draw items previously rendered.
* The view is now automatically redrawn if the view's matrix has changed.
* Update handling has been simplified. There are no matrix-updates anymore.

### Does this PR introduce a breaking change?
- [X] Yes
- [ ] No

* update API

### Other information

Since items were already drawn with the right offset (done by ItemPainter), it makes no sense to have a separate matrix-update. Such an update will result in a redraw anyway.

As a result all matrix-update logic has been removed from GtkView, which resulted in a simpler interface. A nice bonus.

I also considered putting a cache in ItemPainter. It is not easy to pass on data on which item needs updating and which items are removed. Therefore it seemed more logical to keep this data in the view and instead create a separate renderer (RenderedItemPainter), that takes a rendered surface from the view and draws that instead.

BoundingBoxPainter is not needed anymore. It's kept in for now to ease the transition to the new drawing model.

It looks like drawing is considerably slower when the demo app is in full screen. Small windows are fast, bigger ones are slow.

## To do

- [x] There's still an issue where attached elements are not properly redrawn

### CODE REVIEW

**Review by danyeaw — COMMENTED** [review]
These updates look good to me! :+1: 

When testing this using using the demos I am running in to some issues:
1. With demo4 I am getting some very large lagging. For example when I resize the large rectangle and drag out from one of the corners the rectangle size doesn't update for 5-10 seconds.
2. With demo I am getting a lot of artifact corruption which is similar to the gaphor problem we were seeing with the Cairo surface as well.

image

**Comment by danyeaw** [comment]
image

**Comment by amolenaar** [comment]
I'll check GTK4 again.

The artifact problem remains a funny thing. I havn't seen it on Linux, nor macOS. It looks like anti-aliasing is not working too, looking at the lines of the boxes.

**Comment by amolenaar** [comment]
I updated the GTK4 demo to use the RenderedItemPainter too. It looks pretty responsive on macOS.

**Comment by danyeaw** [comment]
@amolenaar It looks like I can only reproduce on SUSE Tumbleweed with XOrg, in Wayland it works fine.

**Comment by amolenaar** [comment]
@danyeaw I installed Tumbleweed on Boxes, and in all works fine with me.

image

It only happens with this branch? Master is just fine?

**Comment by danyeaw** [comment]
@amolenaar Yes master works fine, any thoughts on how I might debug this?

**Comment by amolenaar** [comment]
I suspect the `cairo.RecordingSurface`. I also used it for SVG rendering in Gaphor.

If you revert the change in line 148 of `examples/demo.py`, I expect the render issue is gone.

```diff
-        .append(RenderedItemPainter(view))
+       .append(FreeHandPainter(ItemPainter(view.selection)))
```

But then there's no speedup for subsequent renders. I wonder if we can catch this in a minimal example. E.g. render a rectangle or a circle to a `RecordingSurface` and paint it on a `ImageSurface`. I wonder if that would yield the same result.

**Comment by amolenaar** [comment]
I was just thinking: I added [2 options to GtkView](https://github.com/gaphor/gaphas/pull/224/files#diff-78d3b9ae1bb14826fb5fe03f65281b7cef68112f58207cd17ec2034468b11970R105):

``diff
+            self.set_double_buffered(False)
+            self.set_app_paintable(True)
```

Maybe if you remove those the rendering works properly again?

**Comment by danyeaw** [comment]
@amolenaar Good idea to try that, unfortunately I still have the same issue. Let me try to put together a minimum reproducible canvas drawing example.

**Comment by amolenaar** [comment]
@danyeaw that's a good idea. Maybe ask the Cairo folks then?

**Comment by danyeaw** [comment]
@amolenaar Nice! This new version works great for me. :tada:

**Pull request merged**
