### PR TITLE
Convert from PyGTK to PyGObject

### PR DESCRIPTION
**Pull request by danyeaw**
Conversion from PyGTK to PyGObject (and Gtk+ 2 to 3). Steps taken include:

1. Automatic rename using pygi-convert.sh to do basic find and replace between PyGTK and PyGObject syntax.
2. Fixed some additional Python 3 compatibility cleanups with ez_setup and the tests
3. Completed manual updates to finish the conversion, including the largest update which was to replace the scroll adjustment signals to inherit from Gtk.Scrollable

All tests pass with both Python 2.7.15 and 3.7.0.

### CODE REVIEW

**Comment by wrobell** [comment]
When starting `demo.py` and moving mouse pointer over the canvas:

```
demo.py:139: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button('Add box')
demo.py:148: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button('Add line')
demo.py:158: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button('Zoom in')
demo.py:166: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button('Zoom out')
demo.py:176: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button('Split line')
demo.py:187: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button('Delete focused')
demo.py:198: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.ToggleButton('Record')
demo.py:213: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button('Play back')
demo.py:235: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button('Write demo.png')
demo.py:263: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button('Write demo.svg')
demo.py:290: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button('Dump QTree')
demo.py:299: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button('Pickle (save)')
demo.py:313: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button('Unpickle (load)')
demo.py:329: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button('Unpickle (in place)')
demo.py:346: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  b = Gtk.Button('Reattach (in place)')
AttributeError: 'GtkView' object has no attribute 'do_get_property'
AttributeError: 'GtkView' object has no attribute 'do_get_property'
Traceback (most recent call last):
  File "/home/wrobell/p/1/gaphas/gaphas/view.py", line 899, in on_adjustment_changed
    if adj.value == 0.0: return
AttributeError: 'Adjustment' object has no attribute 'value'
Traceback (most recent call last):
  File "/home/wrobell/p/1/gaphas/gaphas/view.py", line 899, in on_adjustment_changed
    if adj.value == 0.0: return
AttributeError: 'Adjustment' object has no attribute 'value'
AttributeError: 'GtkView' object has no attribute 'do_get_property'
AttributeError: 'GtkView' object has no attribute 'do_get_property'
AttributeError: 'GtkView' object has no attribute 'do_get_property'
AttributeError: 'GtkView' object has no attribute 'do_get_property'
...
```
I am using

- Python 3.7
- python-gobject 3.28.3-2

**Comment by danyeaw** [comment]
@wrobell Awesome, thanks for the feedback! While doing my testing, I didn't try to run the demo, so this was a great suggestion. I fixed some of the errors so far, including the deprecated constructor errors and issues with pickle. There is still a few other errors, so I'll keep on trying to work through those this week.

**Comment by wrobell** [comment]
I have started the `demo.py` again today. The errors are gone when starting, but the canvas of both windows are blank.

After starting the demo, click 'Write demo.png' button. If you take a look at the PNG file - this is what both windows of the demo script shall show.

I hope this helps.

**Comment by wrobell** [comment]
You may also find the following useful (fixes one of the errors on double click):
```
diff --git a/gaphas/tool.py b/gaphas/tool.py
index 27af795..4cc8b82 100644
--- a/gaphas/tool.py
+++ b/gaphas/tool.py
@@ -684,7 +684,7 @@ class TextEditTool(Tool):
         """
         window = Gtk.Window()
         window.set_property('decorated', False)
-        window.set_resize_mode(Gtk.RESIZE_IMMEDIATE)
+        window.set_resize_mode(Gtk.ResizeMode.IMMEDIATE)
         #window.set_modal(True)
         window.set_parent_window(self.view.window)
         buffer = Gtk.TextBuffer()
```

**Comment by danyeaw** [comment]
@wrobell Thanks for helping to fix another error! It looks like there is still more work to do to get the DrawingArea to show up. I did run it using the master branch with Python 2.7, so I see now the behavior the demo is supposed to have. :+1:

**Comment by wrobell** [comment]
Another possible fix:
```
diff --git a/gaphas/aspect.py b/gaphas/aspect.py
index fe695d4..0314471 100644
--- a/gaphas/aspect.py
+++ b/gaphas/aspect.py
@@ -140,22 +140,24 @@ HandleSelection = generic(ItemHandleSelection)
 @HandleSelection.when_type(Element)
 class ElementHandleSelection(ItemHandleSelection):
     CURSORS = (
-        Gdk.CursorType.TOP_LEFT_CORNER,
-        Gdk.CursorType.TOP_RIGHT_CORNER,
-        Gdk.CursorType.BOTTOM_RIGHT_CORNER,
-        Gdk.CursorType.BOTTOM_LEFT_CORNER,
+        'nw-resize',
+        'ne-resize',
+        'se-resize',
+        'sw-resize',
     )
 
     def select(self):
         index = self.item.handles().index(self.handle)
         if index < 4:
-            self.view.window.set_cursor(self.CURSORS[index])
+            display = self.get_display()
+            cursor = Gdk.Cursor.new_from_name(display, CURSORS[index])
+            self.view.get_window().set_cursor(cursor)
 
     def unselect(self):
         from .view import DEFAULT_CURSOR
 
         cursor = Gdk.Cursor(DEFAULT_CURSOR)
-        self.view.window.set_cursor(cursor)
+        self.view.get_window().set_cursor(cursor)
 
 
 
diff --git a/gaphas/tool.py b/gaphas/tool.py
index 4cc8b82..48830e2 100644
--- a/gaphas/tool.py
+++ b/gaphas/tool.py
@@ -686,7 +686,7 @@ class TextEditTool(Tool):
         window.set_property('decorated', False)
         window.set_resize_mode(Gtk.ResizeMode.IMMEDIATE)
         #window.set_modal(True)
-        window.set_parent_window(self.view.window)
+        window.set_parent_window(self.view.get_window())
         buffer = Gtk.TextBuffer()
         text_view = Gtk.TextView()
         text_view.set_buffer(buffer)
```

**Comment by danyeaw** [comment]
@wrobell Thanks for the help on that one as well :+1:
We are getting closer, I'm now not getting errors all over the place when running the demo. Now we need to figure out why the DrawingArea isn't being displayed.

In Python 3.7 I'm also getting an error that I'm not in 2.7, on line 243 of view.py:

            if item.point((ix, iy)) < 0.5:
                return item

The item.point method is just a "pass" function, so it returns a NoneType. Python 3.7 is flagging this as a TypeError for comparing a NoneType and a float. Anyone know what the history of this get_item_at_point method is, it seems like it would never work since measuring the distance from the item to the point is non-functional.

**Comment by danyeaw** [comment]
@amolenaar Got it, I missed that the item could also be an element or line as well, thanks for pointing me in the right direction. :+1:

**Comment by danyeaw** [comment]
I am getting closer. The GtkView is now visible, but it is very narrow and it doesn't get larger through allocation when the window is resized.

**Comment by wrobell** [comment]
One more issue to be solved:

```
diff --git a/gaphas/guide.py b/gaphas/guide.py
index b9da308..a4c5080 100644
--- a/gaphas/guide.py
+++ b/gaphas/guide.py
@@ -307,7 +307,7 @@ class GuidePainter(ItemPaintFocused):
 
         cr = context.cairo
         view = self.view
-        allocation = view.allocation
+        allocation = view.get_allocation()
         w, h = allocation.width, allocation.height
 
         cr.save()
```

Removes the following error when resizing a box
```
AttributeError: 'GtkView' object has no attribute 'allocation'
```

**Comment by danyeaw** [comment]
If I override the do_size_allocate allocation, I can get a window that looks closer to what I was expecting:

```
--- gaphas/view.py	(revision 28a3382b5a6cee296090f47c307c909586ff8bad)
+++ gaphas/view.py	(date 1536803890000)
@@ -822,10 +822,14 @@
         """
         Allocate the widget size ``(x, y, width, height)``.
         """
-        Gtk.DrawingArea.do_size_allocate(self, allocation)
-        self.set_allocation(allocation)
-        self.update_adjustments(allocation)
-        self._qtree.resize((0, 0, allocation.width, allocation.height))
+        print(allocation.width, allocation.height)
+        alloc = Gdk.Rectangle()
+        alloc.width = 500
+        alloc.height = 500
+        Gtk.DrawingArea.do_size_allocate(self, alloc)
+        self.set_allocation(alloc)
+        self.update_adjustments(alloc)
+        self._qtree.resize((0, 0, alloc.width, alloc.height))
 
     def on_size_allocate(self, widget, allocation):
         pass

```
I'm not sure why the allocation.width being passed to the do_size_allocate method is only 15.

screenshot from 2018-09-12 22-08-35

**Comment by danyeaw** [comment]
It's working :+1: I had to override the ScrolledWindow to tell it to horizontally expand.
screenshot from 2018-09-13 22-30-13

**Comment by amolenaar** [comment]
Nice. This looks like the demo app I once built :D :shipit:

**Pull request merged**
