### PR TITLE
Matrix as method

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, ~no~ api changes)
- [ ] Documentation content changes

### What is the current behavior?

The Item protocol feels a bit awkward. On the one hand there's `handles()` and `ports()`, which are normal methods. On the other hand there's `matrix` and `matrix_i2c`, which are implemented as properties.

### What is the new behavior?

I made `matrix` and `matrix_i2c` methods as well. Firstly, because they make type checking easier. Also, this takes away the "overhead" of calling a property.

The alternative is to make `handles` and `ports` properties, which is a tempting alternative.

I'm in doubt what would be the best way to go. The first option (methods) is simple, the second (properties) may result in more idiomatic python.

### Does this PR introduce a breaking change?
- [X] Yes
- [ ] No

@danyeaw What do you think?

### CODE REVIEW

**Review by danyeaw — APPROVED** [review]
It might be a bit simplistic, but I always thought use of properties was a way to avoid use of getters and setters. In the case of matrix, I agree with you that it is more clear and consistent to keep it as a method if it really is one, despite calls being a little more ugly with the extra parenthesis. I agree though that either way would be fine though.

**Comment by amolenaar** [comment]
@danyeaw No more properties then?

**Comment by danyeaw** [comment]
@amolenaar I'm not sure to be honest. Sometimes I have found that updating the docs first might lead us towards the API we want. If i think through it from that angle maybe we do want one of an item's properties to be the matrix it has.

**Comment by amolenaar** [comment]
@danyeaw I'm not sure either. So far my annoyance has always been the `()` when calling `Item.handles()[0]` for example.
I was lead to this approach by errors I got from the type checker. I do not think that's a good way to approach design, though :see_no_evil:.

I'll close this PR. Have a look at the docs and go from there.

**Pull request closed without merging**
